Add disable_shutdown option to Hyper-V builders.
hashicorp/packer-plugin-hyperv pull request #23
Opened 2021-05-02 23:58 UTC by SriRamanujam

Adds a boolean option `disable_shutdown`, in the spirit of the Virtualbox plugin, which when enabled makes the Hyper-V plugin wait for the VM to shut down itself instead of proactively halting it. I happened to need this bit of functionality for the same reason as the original submitter in https://github.com/hashicorp/packer/issues/10630, and since @SwampDragons laid out everything needed I thought I'd give it a shot.

The happy path works for me in my testing. However, ^C doesn't work correctly once Packer goes into the waiting loop. Once the VM goes away, though, Packer cleans up in the usual manner. I'm not sure if that is something I introduced or whether that's because I tested the plugin as its own executable outside of the main Packer executable. I'm not really that well-versed in Go or the plugin structure in general, so I figured I would throw this up and hopefully one of you fine folks could tell me what to fix :D I've attached a log of the issue, in case it helps. 

[ctrl-c not working.txt](https://github.com/hashicorp/packer-plugin-hyperv/files/6412466/ctrl-c.not.working.txt)

Closes #5

2021-05-02 23:59 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer-plugin-hyperv?pullRequest=23)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer-plugin-hyperv?pullRequest=23)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer-plugin-hyperv?pullRequest=23).</sub>

2021-05-03 17:06 UTC, SwampDragons requested changes
This is a great start, thanks for opening this PR!  

I have a couple of suggestions inline, including the fix for your ctrl-C issue. 

Once those are resolved, I'll happily merge. Thanks again for your contribution!!

2021-05-03 17:06 UTC, SwampDragons commented on builder/hyperv/iso/builder.go
> +	// Disable automatic shut down of the virtual machine.
This comment is used to generate our documentation, so it is a good idea to make it more descriptive, both here and in the "vmcx" config. For example, this is the string that generates the Virtualbox documentation for the same feature: 

https://github.com/hashicorp/packer-plugin-virtualbox/blob/main/builder/virtualbox/common/shutdown_config.go#L30-L36

Once that string is updated, call `make generate` from the plugin tool root to regenerate the website docs.

2021-05-03 23:32 UTC, SriRamanujam commented on builder/hyperv/common/step_shutdown.go
> +		select {
I took a swing at moving the `IsRunning` check out into its own goroutine, similar to how the password wait was implemented in the snippet linked. It works on my machine ™️ but if you had something else in mind I'm happy to adjust it.

2021-05-05 20:06 UTC, SwampDragons approved these changes

2021-05-05 20:07 UTC, SwampDragons commented
Just tested this, and it looks great. Thanks!

2021-05-05 20:07 UTC, merged